### ISSUE TITLE
Consider importing BUILD.bazel overlays as static variables

### ISSUE THREAD

**Issue by aaronmondal** [eomii/rules_ll#2]
https://github.com/bazelbuild/bazel/issues/14659 prevents us from leveraging our registry.

We can probably work around this by moving the `third-party-overlays/*.BUILD.bazel` to static variables.

**Comment by aaronmondal** [comment]
Fixed in 01f8732fe2e3e0b04cf81bc372439161fbc64f1b. As soon as the bug is resolved we will switch back, as the current solution doesn't let buildifier analyze the build files.

Registry builds still don't work, but that's an issue with the patches for the clang overlay and not related to the bug.

**Comment by neqochan** [comment]
Bazel bug has been fixed. Waiting for next prerelease so that we can revert.

**Comment by neqochan** [comment]
Switched to upstream bazel CI artifacts that contain the fix. Workaround has been reverted.
