### ISSUE TITLE
The `ll init` command is a bit whacky

### ISSUE THREAD

**Issue by aaronmondal** [eomii/rules_ll#46]
To make sure that we don't accidentally destroy people's workspaces the current `ll init` only appends some contents to files. If one runs the command more than once this will lead to duplicate code in those files which can look somewhat buggy.

We should probably factor the command out into a separate shell script and add more flexibility/checking/whatever to improve its user experience. This should be an actual shell script instead of a nix string template so that we can properly run linters on it. This likely requires changing the structure of the command in a way that every variable is passed as an external argument. I'm thinking something along the lines of invoking it like this in the flake:

```nix
''${ll} \
  --bazelversion=${./.bazelversion} \
  --module=${./examples/MODULE.bazel} \
  --bazelrc=${./examples/.bazelrc}''
```

**Comment by jaroeichler** [comment]
I would suggest including `bazel build|coverage|run|test` as `ll build|coverage|run|test`. We could then define the action environment by defining environment variables in the flake. The shell script could look something like this:
```
#!/bin/bash

while [[ $# -gt 0 ]]; do
    case $1 in
        init)
            shift
            while [[ $# -gt 0 ]]; do
                case $1 in
                    --bazelrc=*)
                        bazelrc="${1#*=}"
                        ;;
                    --bazelversion=*)
                        bazelversion="${1#*=}"
                        ;;
                    --module=*)
                        module="${1#*=}"
                        ;;
                    *)
                        exit 1
                        ;;
                esac
                shift
            done
            if [[
                -n "$bazelrc" &&
                -n "$bazelversion" &&
                -n "$module" &&
                ! -e "WORKSPACE.bazel" &&
                ! -e ".bazelversion" &&
                ! -e "MODULE.bazel" &&
                ! -e ".bazelrc"
                ]]; then
                echo "# Empty." > WORKSPACE.bazel
                echo "${bazelrc}" > .bazelrc
                echo "${bazelversion}" > .bazelversion
                echo "${module}" > MODULE.bazel
            else
                echo ""
                exit 1
            fi
            ;;
        build|coverage|run|test)
            bazelisk $1 \
                --action_env=LL_CFLAGS=$LL_CFLAGS \
                --action_env=LL_LDFLAGS=$LL_LDFLAGS \
                --action_env=LL_DYNAMIC_LINKER=$LL_DYNAMIC_LINKER \
                --action_env=LL_CUDA=$LL_CUDA \
                --action_env=LL_CUDA_RPATH=$LL_CUDA_RPATH \
                --action_env=BAZEL_CXXOPTS=$BAZEL_CXXOPTS \
                --action_env=BAZEL_LINKOPTS=$BAZEL_LINKOPTS \
                "${@:2}"
            ;;
        help)
            echo ""
            ;;
        *)
            exit 1
            ;;
    esac
    shift
done
```

**Comment by aaronmondal** [comment]
I'm worried that this would make it hard to create shell portable shell scripts. It would also make error messages less intuitive (run `ll` but get a `bazel` error).

To make the setup as simple as possible I'm thinking that something like 

```bash
nix flake init  -t github:eomii/rules_ll#init
```

Would be the best way. We now also have a flake and direnv config in the examples. Setting the Bazel files and the nix files up like this seems more user friendly to me than requiring an extra `ll init` step. I tried playing around with the nix flake template feature but couldn't get it to work yet. I think that this would be a good way forward though.

Regarding the environment variables, I'm not sure whether we actually want these to be configurable. At the moment the only entry points are `LL_CFLAGS` and `LL_LDFLAGS` (technically also the CUDA flags with the default toolchain). Using them already makes it hard to reuse caches with remote execution and exporting them (or reading them from an uncontrolled environment) could easily lead to cache invalidation.
