### ISSUE TITLE
Add libxml2-dev to bazel registry

### ISSUE THREAD

**Issue by JannisFengler** [eomii/rules_ll#8]
Building Clang from upstream depends on libxml2-dev. libxml2-dev should be added as external dependency in the [bazel-eomii-registry](https://github.com/eomii/bazel-eomii-registry) and to the dependencies for rules_ll.

**Comment by aaronmondal** [comment]
Turns out this dependency is only required if one wants to work with Windows manifests. Since we don't care about those at the moment, I removed it in d451cb2ab5efb3ea1a86c5a40aca7f545043ec8c. Things should build without libxml2 on the host now.
